### ISSUE TITLE
ConfigEntries' object has no attribute 'async_forward_entry_setups

### ISSUE THREAD

**Issue by maury77** [cgtobi/netatmo_custom#21]
I have HA 2022.7 on rasbperry

after upgrade last version on netatmto custom componenet 

I have this error

Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.10/lib/python3.9/site-packages/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/netatmo/__init__.py", line 164, in async_setup_entry
    await data_handler.async_setup()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/netatmo/data_handler.py", line 153, in async_setup
    await self.hass.config_entries.async_forward_entry_setups(
**AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'**

**Comment by maury77** [comment]
I Solved with upgrade HA to 2022.12
