### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by confucius78** [cgtobi/netatmo_custom#5]
HA version: 2022.02.9

Issue:
The integration is showing as 'failed to setup' after rebooting, although at least the doorbell camera stream has been added.

Log message:
1:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/netatmo/__init__.py", line 218, in async_setup_entry
    cloud.async_listen_connection_change(hass, manage_cloudhook)
AttributeError: module 'homeassistant.components.cloud' has no attribute 'async_listen_connection_change'
```

2: (minute later)
```
Logger: homeassistant
Source: custom_components/netatmo/pyatmo/auth.py:317
Integration: Netatmo
First occurred: 12:06:19 PM (1 occurrences)
Last logged: 12:06:19 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 380, in preload_stream
    stream = await camera.async_create_stream()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 534, in async_create_stream
    source = await self.stream_source()
  File "/config/custom_components/netatmo/camera.py", line 222, in stream_source
    await self._camera.async_update_camera_urls()
  File "/config/custom_components/netatmo/pyatmo/modules/module.py", line 270, in async_update_camera_urls
    temp_local_url = await self._async_check_url(self.vpn_url)
  File "/config/custom_components/netatmo/pyatmo/modules/module.py", line 279, in _async_check_url
    resp = await self.home.auth.async_post_request(url=f"{url}/command/ping")
  File "/config/custom_components/netatmo/pyatmo/auth.py", line 317, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by confucius78** [comment]
Indeed. Did a reinstall after finally updating and no error
